In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [83]:
df=pd.read_csv("DateFruit_Dataset.csv")
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [84]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [85]:
 df.shape

(898, 35)

In [86]:
x=df.drop("Class",axis=1)
y=df["Class"]

In [87]:
df['Class'].unique()
from sklearn.preprocessing import StandardScaler ,LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [88]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [89]:
x_train.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
880,364338,2385.5110,849.6287,548.4377,0.7638,681.0944,0.9874,368969,0.7596,1.5492,...,0.3835,2.5413,2.7010,4.7956,-45702238208,-31309285376,-31791349760,54.5422,46.1706,47.5687
740,343379,2360.4670,919.1130,479.2314,0.8533,661.2138,0.9657,355591,0.6926,1.9179,...,0.8084,13.2536,10.8915,5.0327,-6173152768,-10177111040,-13946608640,20.5354,27.7553,33.2095
231,80044,1059.0460,378.1419,270.6614,0.6983,319.2416,0.9883,80990,0.7521,1.3971,...,-0.1599,2.2247,2.4509,2.2165,-9834114048,-9082079232,-8377428480,54.3915,53.0591,50.5000
388,394009,2279.7581,770.8477,654.0494,0.5292,708.2852,0.9945,396190,0.7632,1.1786,...,1.6654,5.7796,9.1424,7.8056,-18411845632,-23242752000,-23591233536,34.5177,38.9835,38.4695
118,242874,1843.9160,647.9982,479.8817,0.6720,556.0906,0.9906,245181,0.7818,1.3503,...,-0.3694,2.4534,2.2759,2.5079,-46650236928,-40748339200,-32199612416,66.5225,62.6833,56.9092

In [90]:

scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [91]:


#ANN
import torch
import torch.nn as nn
import torch.optim as optim 
from torch.utils.data import DataLoader,TensorDataset

In [92]:
x_train_tensor=torch.tensor(x_train_scaled,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.long)

x_test_tensor=torch.tensor(x_test_scaled,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.long)

In [93]:
train_dataset=TensorDataset(x_train_tensor,y_train_tensor)
test_dataset=TensorDataset(x_test_tensor,y_test_tensor)

In [94]:
train_loder=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32)

In [95]:
#Build teh model
class ANN(nn.Module):
    def __init__(self):
        super(ANN,self).__init__()
        self.model=nn.Sequential(
            nn.Linear(x.shape[1],64),
            nn.ReLU(),



            nn.Linear(64,64),
            nn.ReLU(),

            nn.Linear(64,7)
        )
    def forward(self,x):
        return self.model(x)

In [96]:
model=ANN()
criteria=nn.CrossEntropyLoss()
optimizer=optim.Adam(model.parameters())

In [99]:
#train the NN
epochs=100
for epoch in range (epochs):
    model.train()

    running_loss=0.0
    for xb,yb in train_loder:
        optimizer.zero_grad()
        outputs=model(xb)
        loss=criteria(outputs,yb)
        loss.backward()
        optimizer.step()#parameter uipdate
        running_loss +=loss.item()

    train_loss=running_loss/len(train_loder)
    print(f"epoch ={epoch}/{epochs},loss={train_loss}")

epoch =0/100,loss=0.9216595499411874
epoch =1/100,loss=0.9164754333703414
epoch =2/100,loss=0.9128455195737921
epoch =3/100,loss=0.9307500007359878
epoch =4/100,loss=0.9165797842585522
epoch =5/100,loss=0.9013931699421095
epoch =6/100,loss=0.9031374208305193
epoch =7/100,loss=0.9232681328835695
epoch =8/100,loss=0.8986356076986893
epoch =9/100,loss=0.9038311709528384
epoch =10/100,loss=0.9006093895953634
epoch =11/100,loss=0.917634463828543
epoch =12/100,loss=0.9168927462204642
epoch =13/100,loss=0.9068622226300447
epoch =14/100,loss=0.9086489314618318
epoch =15/100,loss=0.9037055502767148
epoch =16/100,loss=0.9063159693842349
epoch =17/100,loss=0.8959937562113223
epoch =18/100,loss=0.8921860741532367
epoch =19/100,loss=0.8955384544704271
epoch =20/100,loss=0.9083568557449009
epoch =21/100,loss=0.9160958217537921
epoch =22/100,loss=0.8991397152776304
epoch =23/100,loss=0.8961128462915835
epoch =24/100,loss=0.888947852279829
epoch =25/100,loss=0.8972088513167008
epoch =26/100,loss=0.8859448912351028
epoch =27/100,loss=0.9059745151063671
epoch =28/100,loss=0.9085390360459037
epoch =29/100,loss=0.9022155015364938
epoch =30/100,loss=0.8785773295423259
epoch =31/100,loss=0.8880210687284884
epoch =32/100,loss=0.8952015690181566
epoch =33/100,loss=0.8983145382093347
epoch =34/100,loss=0.8759839405184207
epoch =35/100,loss=0.8730824278748553
epoch =36/100,loss=0.8777921666269717
epoch =37/100,loss=0.8924484395462534
epoch =38/100,loss=0.8725220638772716
epoch =39/100,loss=0.8771935571794924
epoch =40/100,loss=0.8691233137379522
epoch =41/100,loss=0.8738822081814641
epoch =42/100,loss=0.8586469033490056
epoch =43/100,loss=0.8709855105565942
epoch =44/100,loss=0.8648019938365273
epoch =45/100,loss=0.8653431327446647
epoch =46/100,loss=0.8549609391585641
epoch =47/100,loss=0.865580959164578
epoch =48/100,loss=0.8711917270784792
epoch =49/100,loss=0.8660174634145654
epoch =50/100,loss=0.8744027096292247
epoch =51/100,loss=0.8544384305891783
epoch =52/100,loss=0.8636314998502317
epoch =53/100,loss=0.8680519617122152
epoch =54/100,loss=0.8533382610134457
epoch =55/100,loss=0.8694084636543108
epoch =56/100,loss=0.8691166924393695
epoch =57/100,loss=0.8768183588981628
epoch =58/100,loss=0.862471650476041
epoch =59/100,loss=0.8638336658477783
epoch =60/100,loss=0.8666764031285825
epoch =61/100,loss=0.8615641645763231
epoch =62/100,loss=0.8668423256148463
epoch =63/100,loss=0.8563589946083401
epoch =64/100,loss=0.8580421287080516
epoch =65/100,loss=0.8710332305535026
epoch =66/100,loss=0.8621020498483077
epoch =67/100,loss=0.8773920147315316
epoch =68/100,loss=0.8563501277695531
epoch =69/100,loss=0.8495070092056108
epoch =70/100,loss=0.8674957208011461
epoch =71/100,loss=0.8638393231060194
epoch =72/100,loss=0.8500180257403332
epoch =73/100,loss=0.8618629341540129
epoch =74/100,loss=0.8631022365196891
epoch =75/100,loss=0.8612543655478436
epoch =76/100,loss=0.8676886908386064
epoch =77/100,loss=0.8601457191550214
epoch =78/100,loss=0.8681622095729994
epoch =79/100,loss=0.8603551102721173
epoch =80/100,loss=0.862908529198688
epoch =81/100,loss=0.8619999470918075
epoch =82/100,loss=0.8728753457898679
epoch =83/100,loss=0.8527834298818008
epoch =84/100,loss=0.8637754917144775
epoch =85/100,loss=0.8665931613548942
epoch =86/100,loss=0.8534233583056409
epoch =87/100,loss=0.876438584016717
epoch =88/100,loss=0.8537316011345905
epoch =89/100,loss=0.8676444836284803
epoch =90/100,loss=0.8522229129853456
epoch =91/100,loss=0.8738778337188389
epoch =92/100,loss=0.8606166334255881
epoch =93/100,loss=0.865082878133525
epoch =94/100,loss=0.8727397996446361
epoch =95/100,loss=0.8812993376151376
epoch =96/100,loss=0.8694507376007412
epoch =97/100,loss=0.866420258646426
epoch =98/100,loss=0.8539550796799038
epoch =99/100,loss=0.8672311552192854

In [101]:
#evaluate
model.eval()
total=0
correct=0
with torch.no_grad():
    for xb,yb in test_loader:
        outputs=model(xb)
        max_val,predicted=torch.max(outputs,1)
        correct+=(predicted==yb).sum().item()
        total+=yb.size(0)  #actual sample in each batch
print("total value:",total)
print("correct values:",correct)
print("accuracy :",correct/total*100)

total value: 180
correct values: 109
accuracy : 60.55555555555555